language: node_js
node_js: 
    - "12.13.1"
dist: trusty
services:
    - mongodb
    - redis-server
env:
    - NODE_ENV=ci REDIS_URL=redis://127.0.0.1:6379 PORT=8082 MONGODB_URI=mongodb://127.0.0.1:27017/PortfolioCI JWT_SECRET=uyiuytiouyipuyoigvgcfhgcbvcb
cache:
    directories:
        - node_modules
        - client/node_modules
install:
    - npm install
    - cd client && npm install
    - npm run build && cd ..
script:
    - hohup npm run start &
    - sleep 3
    - npm run test-ci